#!/bin/sh

BOARD=@@DEFAULT_BOARD@@

case ${BOARD} in
	odroidc5)
		echo "Use preinstalled /etc/xdg/weston/weston.ini"
		;;
	*)
		rm -f /etc/xdg/weston/weston.ini
		;;
esac

dpkg-reconfigure odroid-kiosk-weston
