#!/bin/sh

REPO=ppa:deadsnakes/ppa

if [ -z $(which add-apt-repository) ]; then
apt update -y
apt install @@DEFAULT_APT_OPTIONS@@ \
		software-properties-common
fi

add-apt-repository ${REPO} -y
apt update -y

