#!/bin/sh

BOARD=@@DEFAULT_BOARD@@
OVERLAYS="rknpu"

if [ -f /boot/config.ini ]; then
	case ${BOARD} in
		odroidm1)
			OVERLAYS="${OVERLAYS} ov5647"
			;;
	esac

	sed -i '/generic/,/overlays/ s/^\(overlays=".*\)"/\1 '"${OVERLAYS}"'"/' /boot/config.ini
fi
