#!/bin/sh

CUSTOM_USER=@@DEFAULT_USER@@
USER=${CUSTOM_USER:-odroid}
HOME=/home/${USER}
RKNN=${HOME}/rknn-toolkit2/rknpu2/runtime/Linux/librknn_api/aarch64/librknnrt.so
WHL=${HOME}/rknn-toolkit2/rknn-toolkit-lite2/packages/rknn_toolkit_lite2-2.1.0-cp39-cp39-linux_aarch64.whl
MPP_PATH=${HOME}/rknn-toolkit2/rknpu2/examples/3rdparty/mpp/Linux/aarch64

echo "I: cloning rknn-toolkit2 repository"
git clone https://github.com/hardkernel/rknn-toolkit2 ${HOME}/rknn-toolkit2 --depth=1
git clone https://github.com/hardkernel/rknn_model_zoo ${HOME}/rknn_model_zoo --depth=1

echo "I: creating python virtual environment (using: Pyhton3.9)"
python3.9 -m venv ${HOME}/.rknn

[ -f ${WHL} ] && ${HOME}/.rknn/bin/python3.9 -m pip install ${WHL}
yes | ${HOME}/.rknn/bin/python3.9 -m pip install opencv-python

echo "I: setting up environment"
[ -f "${MPP_PATH}/librockchip_mpp.so.0" ] \
      	&& [ -L "${MPP_PATH}/librockchip_mpp.so.1" ] \
       	&& [ -L "${MPP_PATH}/librockchip_mpp.so" ] \
	&& cd ${MPP_PATH} \
	&& ln -sf librockchip_mpp.so.0 librockchip_mpp.so.1 \
	&& ln -sf librockchip_mpp.so.0 librockchip_mpp.so \
	&& cd ${HOME}
chown -R ${USER}:${USER} ${HOME}/rknn-toolkit2/
chown -R ${USER}:${USER} ${HOME}/rknn_model_zoo/
chown -R ${USER}:${USER} ${HOME}/.rknn/
[ -f ${RKNN} ] && cp ${RKNN} /usr/lib/librknnrt.so

# activate venv at start up
echo "source ${HOME}/.rknn/bin/activate" >> ${HOME}/.bashrc

