#!/bin/sh

mkdir -p $(dirname $(realpath -m /etc/resolv.conf))

cat>/etc/resolv.conf<<__EOF
nameserver 127.0.0.53
__EOF

if [ ! "x@@DEFAULT_LINUXFACTORY@@" = "x" ]; then
	echo "@@DEFAULT_LINUXFACTORY@@ ppa.linuxfactory.or.kr" >> /etc/hosts
fi

cat /etc/hosts
