[core]
locking=false
idle-time=0
#shell=desktop-shell.so
#xwayland=true
gbm-format=abgr8888
#repaint-window=16
background-color=0x00ffffff
background-type=scale
panel-position=none
startup-animation=none
close-animation=none

[shell]
background-color=0xff002244
clock-format=minutes
locking=false

[input-method]
path=/usr/libexec/weston-keyboard

#[xwayland]
#path=/usr/bin/Xwayland

#[autolaunch]
#path=/usr/share/odroid-kiosk-weston/weston-autostart.sh
#watch=true

[output]
name=HDMI-A-1
#mode=1920x1080@60
mode=3840x2160@60
#ui-size=3840x2160
ui-size=1920x1080
priority=9
